name: Jinji Monitor
on:
  workflow_dispatch:
  schedule:
    - cron: '7 0 * * *' # 日本時間の毎日午前0907に実行

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install requests beautifulsoup4 pdfplumber
    - name: Run logic
    env:
        PYTHONUNBUFFERED: "1" # ← ★この2行を必ず追加してください
      run: python main.py
